### ISSUE TITLE
Sortable for pages

### ISSUE THREAD

**Issue by lilUnkelDemon** [4xmen/Anubias-Desktop#6]
we need adding sortable to pages .

![photo_2023-03-29_03-15-18](https://user-images.githubusercontent.com/107075450/228391143-40088bf4-5844-4b24-9233-7bd671d69e69.jpg)

**Comment by farzady** [comment]
reasonable !

**Comment by A1Gard** [comment]
WIP: Thank you dear Amir, I'm working on this.

**Comment by A1Gard** [comment]
Done!

b7ff0a797847c6
