### ISSUE TITLE
can't download software or work with the web app

### ISSUE THREAD

**Issue by aliansgp** [4xmen/Anubias-Desktop#7]
Is the project canceled?
I can't download any software or work with web app
Is this situation temporary?

**Comment by Saeid13700416** [comment]
I didn't understand your question, I think you got it wrong

در تاریخ سه‌شنبه ۴ آوریل ۲۰۲۳،‏ ۰۹:۴۰ ali abdollahian <
***@***.***> نوشت:

**Comment by A1Gard** [comment]
OFC not, we are working on version 2, You can use offilne app of version version 1

**Comment by Saeid13700416** [comment]
Awesome, thanks!

در تاریخ یکشنبه ۹ آوریل ۲۰۲۳،‏ ۰۶:۳۶ A1Gard ***@***.***> نوشت:
